const express = require("express");
// const bodyParser = require("body-parser")
const router = express.Router();

const userSignUpController = require("../controller/userSignUp");
const userSignInController = require("../controller/userSignIn");
const userDetailsController = require("../controller/userDetails");
const authToken = require("../middleware/authToken");
const userSignOutController = require("../controller/userSignOut");
const allUsersController = require("../controller/allUsers");
const updateUserController = require("../controller/updateUser");
const addProductController = require("../controller/addProduct");
const allProductsController = require("../controller/allProducts");
const updateProductController = require("../controller/updateProduct");
const categoryProductOneController = require("../controller/categoryProductOne");
const categoryProductsController = require("../controller/categoryProducts");
const productDetailsController = require("../controller/productDetails");
const addToCartController = require("../controller/addToCart");
const cartProductsCountController = require("../controller/cartProductsCount");
const productCartStatusController = require("../controller/productCartStatus");
const cartProductsController = require("../controller/cartProducts");
const updateCartProduct = require("../controller/updateCartProduct");
const removeCartProduct = require("../controller/removeCartProduct");
const searchProductController = require("../controller/searchProduct");
const filterProductsController = require("../controller/filterProducts");
const paymentController = require("../controller/payment");
const stripeWebhook = require("../controller/stripeWebhook");
const orderController = require("../controller/orders");
const addAddressController = require("../controller/addAddress");
const addressController = require("../controller/address");
const updateAddressController = require("../controller/updateAddress");
const forgotPasswordController = require("../controller/forgotPassword");
const resetPasswordController = require("../controller/resetPassword");
const allOrdersController = require("../controller/allOrders");
const addOrderController = require("../controller/addOrder");
const updateOrderController = require("../controller/updateOrder");

router.post("/sign-up", userSignUpController);
router.post("/sign-in", userSignInController);
router.get("/user-details", authToken, userDetailsController);
router.get("/sign-out", userSignOutController);
router.get("/all-users", authToken, allUsersController);
router.post("/update-user", authToken, updateUserController);
router.post("/add-product", authToken, addProductController);
router.get("/all-products", allProductsController);
router.post("/update-product", authToken, updateProductController);
router.get("/category-product-one", categoryProductOneController);
router.post("/category-products", categoryProductsController);
router.post("/product-details", productDetailsController);
router.post("/add-to-cart", authToken, addToCartController);
router.get("/cart-products-count", authToken, cartProductsCountController);
router.get("/product-cart-status", authToken, productCartStatusController);
router.get("/cart-products", authToken, cartProductsController);
router.post("/update-cart-product", authToken, updateCartProduct);
router.post("/remove-cart-product", authToken, removeCartProduct);
router.get("/search-product", searchProductController);
router.post("/filter-products", filterProductsController);
router.post("/payment", authToken, paymentController);
router.post("/stripe-webhook", stripeWebhook);
// router.post('/stripe-webhook', bodyParser.raw({ type: 'application/json' }), stripeWebhook);

router.get("/orders", authToken, orderController);
router.post("/add-address", authToken, addAddressController);
router.get("/address", authToken, addressController);
router.post("/update-address", authToken, updateAddressController);
router.post("/forgot-password", forgotPasswordController);
router.put("/reset-password", resetPasswordController);
router.get("/all-orders", authToken, allOrdersController);
router.post("/add-order", authToken, addOrderController);
router.post("/update-order", authToken, updateOrderController);

module.exports = router;
